package com.roksanagulewska.recipent.tags

enum class DefaultFoodTag(name: String) {
    //Diet tag names
    VEGETARIAN("vegetarian"),
    VEGAN("vegan"),
    KETO("keto"),
    PALEO("paleo"),
    LOW_CARB("low carb"),
    LOW_FAT("low fat"),
    HIGH_PROTEIN("high protein"),
    DAIRY_FREE("dairy free"),
    GLUTEN_FREE("gluten free"),

    //Ingredients tag names
    TOMATO("tomato"),
    POTATO("potato"),
    ONION("onion"),
    GARLIC("garlic"),
    BELL_PEPPER("bell pepper"),
    CUCUMBER("cucumber"),
    CARROT("carrot"),
    SPINACH("spinach"),
    LETTUCE("lettuce"),
    BROCCOLI("broccoli"),
    MUSHROOM("mushroom"),
    CHICKEN("chicken"),
    BEEF("beef"),
    PORK("pork"),
    FISH("fish"),
    SHRIMP("shrimp"),
    EGG("egg"),
    CHEESE("cheese"),
    BUTTER("butter"),
    MILK("milk"),
    BASIL("basil"),
    OREGANO("oregano"),
    THYME("thyme"),
    ROSEMARY("rosemary"),
    CILANTRO("cilantro"),
    PARSLEY("parsley"),
    DILL("dill"),
    GINGER("ginger"),
    TURMERIC("turmeric"),
    CINNAMON("cinnamon"),
    NUTMEG("nutmeg"),
    CLOVE("clove"),
    VANILLA("vanilla"),
    LEMON("lemon"),
    LIME("lime"),
    ORANGE("orange"),
    APPLE("apple"),
    BANANA("banana"),
    KIWI("kiwi"),
    PINEAPPLE("pineapple"),
    RICE("rice"),
    PASTA("pasta"),
    BREAD("bread"),
    OLIVE_OIL("olive oil"),
    SUGAR("sugar"),
    FLOUR("flour")
}